// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.grpc.godemo;

public final class GoGrpcUtilx {
  private GoGrpcUtilx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code AgentStatus}
   */
  public enum AgentStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Status1 = 0;</code>
     */
    Status1(0),
    /**
     * <code>Status2 = 1;</code>
     */
    Status2(1),
    /**
     * <code>Status3 = 2;</code>
     */
    Status3(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Status1 = 0;</code>
     */
    public static final int Status1_VALUE = 0;
    /**
     * <code>Status2 = 1;</code>
     */
    public static final int Status2_VALUE = 1;
    /**
     * <code>Status3 = 2;</code>
     */
    public static final int Status3_VALUE = 2;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AgentStatus valueOf(int value) {
      return forNumber(value);
    }

    public static AgentStatus forNumber(int value) {
      switch (value) {
        case 0: return Status1;
        case 1: return Status2;
        case 2: return Status3;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AgentStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AgentStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AgentStatus>() {
            @Override
            public AgentStatus findValueByNumber(int number) {
              return AgentStatus.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return AgentStatusVerifier.INSTANCE;
    }

    private static final class AgentStatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new AgentStatusVerifier();
            @Override
            public boolean isInRange(int number) {
              return AgentStatus.forNumber(number) != null;
            }
          };

    private final int value;

    private AgentStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AgentStatus)
  }

  public interface AppSignOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppSign)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string devphyid = 1;</code>
     * @return The devphyid.
     */
    String getDevphyid();
    /**
     * <code>string devphyid = 1;</code>
     * @return The bytes for devphyid.
     */
    com.google.protobuf.ByteString
        getDevphyidBytes();
  }
  /**
   * Protobuf type {@code AppSign}
   */
  public  static final class AppSign extends
      com.google.protobuf.GeneratedMessageLite<
          AppSign, AppSign.Builder> implements
      // @@protoc_insertion_point(message_implements:AppSign)
      AppSignOrBuilder {
    private AppSign() {
      devphyid_ = "";
    }
    public static final int DEVPHYID_FIELD_NUMBER = 1;
    private String devphyid_;
    /**
     * <code>string devphyid = 1;</code>
     * @return The devphyid.
     */
    @Override
    public String getDevphyid() {
      return devphyid_;
    }
    /**
     * <code>string devphyid = 1;</code>
     * @return The bytes for devphyid.
     */
    @Override
    public com.google.protobuf.ByteString
        getDevphyidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(devphyid_);
    }
    /**
     * <code>string devphyid = 1;</code>
     * @param value The devphyid to set.
     */
    private void setDevphyid(
        String value) {
      value.getClass();
  
      devphyid_ = value;
    }
    /**
     * <code>string devphyid = 1;</code>
     */
    private void clearDevphyid() {
      
      devphyid_ = getDefaultInstance().getDevphyid();
    }
    /**
     * <code>string devphyid = 1;</code>
     * @param value The bytes for devphyid to set.
     */
    private void setDevphyidBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      devphyid_ = value.toStringUtf8();
      
    }

    public static AppSign parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSign parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSign parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSign parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSign parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSign parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSign parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AppSign parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AppSign parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static AppSign parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AppSign parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AppSign parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(AppSign prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code AppSign}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          AppSign, Builder> implements
        // @@protoc_insertion_point(builder_implements:AppSign)
        AppSignOrBuilder {
      // Construct using com.grpc.godemo.GoGrpcUtil.AppSign.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string devphyid = 1;</code>
       * @return The devphyid.
       */
      @Override
      public String getDevphyid() {
        return instance.getDevphyid();
      }
      /**
       * <code>string devphyid = 1;</code>
       * @return The bytes for devphyid.
       */
      @Override
      public com.google.protobuf.ByteString
          getDevphyidBytes() {
        return instance.getDevphyidBytes();
      }
      /**
       * <code>string devphyid = 1;</code>
       * @param value The devphyid to set.
       * @return This builder for chaining.
       */
      public Builder setDevphyid(
          String value) {
        copyOnWrite();
        instance.setDevphyid(value);
        return this;
      }
      /**
       * <code>string devphyid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevphyid() {
        copyOnWrite();
        instance.clearDevphyid();
        return this;
      }
      /**
       * <code>string devphyid = 1;</code>
       * @param value The bytes for devphyid to set.
       * @return This builder for chaining.
       */
      public Builder setDevphyidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDevphyidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AppSign)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new AppSign();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "devphyid_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<AppSign> parser = PARSER;
          if (parser == null) {
            synchronized (AppSign.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<AppSign>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AppSign)
    private static final AppSign DEFAULT_INSTANCE;
    static {
      AppSign defaultInstance = new AppSign();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AppSign.class, defaultInstance);
    }

    public static AppSign getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppSign> PARSER;

    public static com.google.protobuf.Parser<AppSign> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AppSignResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppSignResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>string retmsg = 2;</code>
     * @return The retmsg.
     */
    String getRetmsg();
    /**
     * <code>string retmsg = 2;</code>
     * @return The bytes for retmsg.
     */
    com.google.protobuf.ByteString
        getRetmsgBytes();
  }
  /**
   * Protobuf type {@code AppSignResponse}
   */
  public  static final class AppSignResponse extends
      com.google.protobuf.GeneratedMessageLite<
          AppSignResponse, AppSignResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:AppSignResponse)
      AppSignResponseOrBuilder {
    private AppSignResponse() {
      retmsg_ = "";
    }
    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retcode_;
    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    @Override
    public int getRetcode() {
      return retcode_;
    }
    /**
     * <code>int32 retcode = 1;</code>
     * @param value The retcode to set.
     */
    private void setRetcode(int value) {
      
      retcode_ = value;
    }
    /**
     * <code>int32 retcode = 1;</code>
     */
    private void clearRetcode() {
      
      retcode_ = 0;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private String retmsg_;
    /**
     * <code>string retmsg = 2;</code>
     * @return The retmsg.
     */
    @Override
    public String getRetmsg() {
      return retmsg_;
    }
    /**
     * <code>string retmsg = 2;</code>
     * @return The bytes for retmsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getRetmsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(retmsg_);
    }
    /**
     * <code>string retmsg = 2;</code>
     * @param value The retmsg to set.
     */
    private void setRetmsg(
        String value) {
      value.getClass();
  
      retmsg_ = value;
    }
    /**
     * <code>string retmsg = 2;</code>
     */
    private void clearRetmsg() {
      
      retmsg_ = getDefaultInstance().getRetmsg();
    }
    /**
     * <code>string retmsg = 2;</code>
     * @param value The bytes for retmsg to set.
     */
    private void setRetmsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      retmsg_ = value.toStringUtf8();
      
    }

    public static AppSignResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSignResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSignResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSignResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSignResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AppSignResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AppSignResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AppSignResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AppSignResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static AppSignResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AppSignResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AppSignResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(AppSignResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code AppSignResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          AppSignResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:AppSignResponse)
        AppSignResponseOrBuilder {
      // Construct using com.grpc.godemo.GoGrpcUtil.AppSignResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 retcode = 1;</code>
       * @return The retcode.
       */
      @Override
      public int getRetcode() {
        return instance.getRetcode();
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        copyOnWrite();
        instance.setRetcode(value);
        return this;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        copyOnWrite();
        instance.clearRetcode();
        return this;
      }

      /**
       * <code>string retmsg = 2;</code>
       * @return The retmsg.
       */
      @Override
      public String getRetmsg() {
        return instance.getRetmsg();
      }
      /**
       * <code>string retmsg = 2;</code>
       * @return The bytes for retmsg.
       */
      @Override
      public com.google.protobuf.ByteString
          getRetmsgBytes() {
        return instance.getRetmsgBytes();
      }
      /**
       * <code>string retmsg = 2;</code>
       * @param value The retmsg to set.
       * @return This builder for chaining.
       */
      public Builder setRetmsg(
          String value) {
        copyOnWrite();
        instance.setRetmsg(value);
        return this;
      }
      /**
       * <code>string retmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetmsg() {
        copyOnWrite();
        instance.clearRetmsg();
        return this;
      }
      /**
       * <code>string retmsg = 2;</code>
       * @param value The bytes for retmsg to set.
       * @return This builder for chaining.
       */
      public Builder setRetmsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRetmsgBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AppSignResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new AppSignResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "retcode_",
              "retmsg_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<AppSignResponse> parser = PARSER;
          if (parser == null) {
            synchronized (AppSignResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<AppSignResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AppSignResponse)
    private static final AppSignResponse DEFAULT_INSTANCE;
    static {
      AppSignResponse defaultInstance = new AppSignResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AppSignResponse.class, defaultInstance);
    }

    public static AppSignResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppSignResponse> PARSER;

    public static com.google.protobuf.Parser<AppSignResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
